trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'cib-demo-dev'
  location: 'East US'
  templateFile: 'ARMTemplateForFactory.bicep'
  parametersFile: 'parameters/dev.parameters.json'

stages:
- stage: Build
  displayName: 'Build Bicep Template'
  jobs:
  - job: BuildBicep
    displayName: 'Build and Validate Bicep Template'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<Your Azure Service Connection Name>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Building the Bicep file..."
          az bicep build --file $(templateFile)
      displayName: 'Build Bicep'

- stage: Deploy
  displayName: 'Deploy Resources'
  dependsOn: Build
  jobs:
  - deployment: DeployResources
    displayName: 'Deploy Bicep Template'
    environment: '$(resourceGroup)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '<Your Azure Service Connection Name>'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating resource group if it doesn't exist..."
                az group create --name $(resourceGroup) --location "$(location)"
                echo "Deploying resources in complete mode..."
                az deployment group create --mode Complete --resource-group $(resourceGroup) --template-file $(templateFile) --parameters @$(parametersFile) --parameters SharePointOnlineList_Jan28_servicePrincipalKey=$(SPKey)
            displayName: 'Deploy Bicep Template'
