name: Azure Deployment

# Trigger the workflow on push or pull request events for dev, uat, and main branches.
on:
  push:
    branches:
      - dev
      - uat
      - main
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code.
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI with the specified version.
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: '2.40.0'
          inlineScript: 'echo "Azure CLI is set up"'

      # Step 3: Set environment variables based on the branch.
      # Mapping:
      #   main  -> Production deployment
      #   uat   -> UAT deployment (shares the same credentials as dev)
      #   dev   -> Development deployment
      - name: Set environment variables
        id: setenv
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Production deployment"
            echo "PARAM_FILE=parameters/prod.parameters.json" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=cib-demo-prod" >> $GITHUB_ENV
            echo "AZURE_CREDS=$(echo '${{ secrets.AZURE_CREDENTIALS_PROD }}' | tr -d '\n')" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "UAT deployment"
            echo "PARAM_FILE=parameters/uat.parameters.json" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=cib-demo-uat" >> $GITHUB_ENV
            echo "AZURE_CREDS=$(echo '${{ secrets.AZURE_CREDENTIALS_DEV }}' | tr -d '\n')" >> $GITHUB_ENV
          else
            echo "Development deployment"
            echo "PARAM_FILE=parameters/dev.parameters.json" >> $GITHUB_ENV
            echo "RESOURCE_GROUP=cib-demo-dev" >> $GITHUB_ENV
            echo "AZURE_CREDS=$(echo '${{ secrets.AZURE_CREDENTIALS_DEV }}' | tr -d '\n')" >> $GITHUB_ENV
          fi

      # Step 4: Log in to Azure using the credentials set above.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDS }}

      # Step 5: Build the Bicep template to validate its syntax.
      - name: Build Bicep Template
        run: az bicep build --file ARMTemplateForFactory.bicep

      # Step 6: Create the resource group if it does not already exist.
      - name: Create Resource Group (if needed)
        run: az group create --name ${{ env.RESOURCE_GROUP }} --location "East US"

      # Step 7: Deploy the Bicep template.
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --mode Complete \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ARMTemplateForFactory.bicep \
            --parameters @${{ env.PARAM_FILE }} \
            --parameters SharePointOnlineList_Jan28_servicePrincipalKey="${{ secrets.SP_KEY }}"
