name: Azure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: '2.40.0'
          inlineScript: 'echo "Azure CLI is set up"'

      # Step 3: Set environment variables
      - name: Set environment variables
        run: |
          echo "RESOURCE_GROUP=CIB-DL" >> $GITHUB_ENV
          echo "AZURE_CREDS=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | tr -d '\n')" >> $GITHUB_ENV
          echo "FACTORY_NAME=data-modernization" >> $GITHUB_ENV
          echo "PARAM_FILE=parameters/vanilla.parameters.json" >> $GITHUB_ENV

      # Step 4: Debug credential environment variable
      - name: Debug AZURE_CREDS
        run: |
          if [ -z "$AZURE_CREDS" ]; then
            echo "AZURE_CREDS is empty"
            exit 1
          else
            echo "AZURE_CREDS is set"
          fi

      # Step 5: Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDS }}

      # Step 6: Validate the Bicep file compiles
      - name: Build Bicep Template
        run: az bicep build --file templates/ARMTemplateForFactory.bicep

      # Step 7: Create Resource Group (if needed)
      - name: Create Resource Group
        run: az group create --name ${{ env.RESOURCE_GROUP }} --location "East US"

      # Step 8: Deploy the Bicep template
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --mode Complete \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file templates/ARMTemplateForFactory.bicep \
            --parameters @$PARAM_FILE \
            --parameters SharePointOnlineList_Jan28_servicePrincipalKey="${{ secrets.SP_KEY }}" \
            --parameters factoryName="${{ env.FACTORY_NAME }}" \
            --parameters vpnSharedKey="${{ secrets.VPN_SHARED_KEY }}"
